// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddwordbuttonController from "./addwordbutton_controller"
application.register("addwordbutton", AddwordbuttonController)

import EditController from "./edit_controller"
application.register("edit", EditController)

import EditphraseController from "./editphrase_controller"
application.register("editphrase", EditphraseController)

import GoogleMapsController from "./google_maps_controller"
application.register("google-maps", GoogleMapsController)

import GoogleSearchController from "./google_search_controller"
application.register("google-search", GoogleSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import SavewordbuttonController from "./savewordbutton_controller"
application.register("savewordbutton", SavewordbuttonController)

import SearchPracticesController from "./search_practices_controller"
application.register("search-practices", SearchPracticesController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
